const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "./images/shops/AngleBar.jpeg",
      name: "Angle Bar",
      price: "640",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 8,
      cover: "./images/shops/Bubong.jpeg",
      name: "Apo EPR Red",
      price: "98.74",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 9,
      cover: "./images/shops/Boysen.jpeg",
      name: "Boysen Pacific Paint",
      price: "836.039",
      sizes: ['1L', '2L', '5L'],
    },
    {
      id: 10,
      cover: "./images/shops/CocoLumber.jpeg",
      name: "Coco Lumber",
      price: "131.3",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 11,
      cover: "./images/shops/CycloneWire3ft.jpeg",
      name: "Cyclone Wire 3ft 2x2",
      price: "250",
      sizes: ['3ft', '5ft', '6ft'],
    },
    {
      id: 12,
      cover: "./images/shops/DefRerolledSteel.jpeg",
      name: "Def Rerolled Steel Bar",
      price: "68.84",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 13,
      cover: "./images/shops/ElectricalTape.jpeg",
      name: "Electrical Tape",
      price: "22.06",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 14,
      cover: "./images/shops/Paint Brush 4.jpeg",
      name: "Paint Brush",
      price: "71.68",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 15,
      cover: "./images/shops/Plywood.jpeg",
      name: "Ply wood",
      price: "800",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 16,
      cover: "./images/shops/Powerlinepipe.jpeg",
      name: "Powerline Pipe 1/2",
      price: "92.7",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 17,
      cover: "./images/shops/RerolledBar.jpeg",
      name: "Rerolled Bar 2.2",
      price: "88",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 18,
      cover: "./images/shops/SteelMatting.jpeg",
      name: "Steel Matting",
      price: "715",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 19,
      cover: "./images/shops/Vulcaseal 1-2L.jpeg",
      name: "Vukcaseal 1/2 L",
      price: "264.66",
      sizes: ['Small', 'Medium', 'Large'],
    },
    {
      id: 20,
      cover: "./images/shops/FlatBar.jpeg",
      name: "Flat Bar 1/4 1w",
      price: "250",
      sizes: ['Small', 'Medium', 'Large'],
    },
    
   
  ],
}
export default Sdata
